### ISSUE TITLE
[3pt] My reservations Page: Member 2

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/rideease-backend#11]
When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).

**Comment by ngeelani48** [comment]
Created the reservation page where users can see his/her reserved cars:



![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/117263981/44daad55-0c13-4a0d-bd33-f71eb6bba7e2)
