### ISSUE TITLE
[2pt] Admin access: Member 4

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/rideease-backend#13]
Make sure that the "Add item" and "Delete item" links are accessible only by users who are admins.

**Comment by ismailmunyentwari9** [comment]
![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/79504482/86a413a9-db31-4679-b1e7-fa80099f5164)
![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/79504482/1bdbc7f6-2c4c-4a44-8fb0-27a6a8b33468)

**Comment by ismailmunyentwari9** [comment]
# What I have Done On this Part Of project 🌳 

Grant[Add] Ability To the Admin User Only to prfom

- [ ] Deletion with Delete Button Funtionalities
- [ ] Add With Add Button Funtionalities
