### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by batoorsohail** [shubhambhoyar077/rideease-backend#15]
Hi reviewer, 👋 
We are 5 people working on this project:

- Member 1 = @shubhambhoyar077 
- Member 2 = @ngeelani48 
- Member 3 = @batoorsohail 
- Member 4 = @ismailmunyentwari9 
- Member 5 = @Caren-Koroeny 

![Kanban](https://github.com/shubhambhoyar077/rideease-backend/assets/100614799/9bd992c1-c21a-4356-825c-f965c5f3ee77)
[Link to our Kanban Board](https://github.com/users/shubhambhoyar077/projects/6/views/1)

**Comment by Meltrust** [comment]
Hi @batoorsohail,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete! 
Congratulations! 🎉 

### To highlight

- All tasks have descriptions, have been assigned, and have been pointed fairly✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
