### ISSUE TITLE
[2pt] Navigation panel: Member 2

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/rideease-backend#4]
In the navigation panel, the user can see links to:
-   Cars items that you selected as a theme.
-   "Reserve" form.
-   "My reservations".
-   "Add cars item that you selected as a theme" (the link is visible to everybody).
-   "Delete cars item that you selected as a theme" (the link is visible to everybody).

**Comment by ngeelani48** [comment]
Created the Navigation Panel (Sidebar) and the final look is as:

![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/117263981/a24522bd-6bef-4a25-9e38-3b9ba621a96c)
