### ISSUE TITLE
[3pt] Main Page: Member 3

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/rideease-backend#5]
On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).
<img width="832" alt="list" src="https://github.com/shubhambhoyar077/rideease-backend/assets/70534992/67035c92-e41b-4f81-8b7f-fae1f5706231">

**Comment by batoorsohail** [comment]
The final look of HomePage:


![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/100614799/e90c4988-4bbb-4b82-9fad-85eb9d5c9121)
