### ISSUE TITLE
[3pt] Details page: Member 4

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/rideease-backend#6]
When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).

  In the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).
<img width="831" alt="details" src="https://github.com/shubhambhoyar077/rideease-backend/assets/70534992/b45c2120-7112-4122-878b-6a253b036959">

**Comment by ismailmunyentwari9** [comment]
# What I have done on this part of our project 🥇 

- [ ] Add click functionality to all names of the Car Items in the store 
- [ ] Render Car Details After clicking its name 
- [ ] Create Car Details Page Showing: 

- Big Image Of clicked Car
- Details like names and price of the car
- Reservation Button for the clccled car
