### ISSUE TITLE
[2pt] App responsive: Member 5

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/rideease-backend#8]
Make the app responsive, creating both mobile and desktop versions.

**Comment by Caren-Koroeny** [comment]
### Final Screenshot

Desktop version


![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/55842414/368b5ef1-14f5-4013-afc7-2f69df5f35d8)

Mobile version


![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/55842414/f81dbf4f-1254-4c62-a7f5-a5708f69eb87)

![Image](https://github.com/shubhambhoyar077/rideease-backend/assets/55842414/3196531e-2a2f-418a-a754-e263626cc3a3)
